# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "08c1bee40e8e29bed9918a0b8ac2dacd"
name = "nitro 2 backup"
handle = "nitro-2-backup"
application_url = "https://nitro-shopify-visitor-intelligence.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ravistore-shop.myshopify.com"

[access_scopes]
scopes = "read_customers,read_orders,read_products"

[auth]
redirect_urls = [
  "https://nitro-shopify-visitor-intelligence.onrender.com/auth/callback",
  "https://nitro-shopify-visitor-intelligence.onrender.com/auth/shopify/callback",
  "https://nitro-shopify-visitor-intelligence.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"
